version: 2.1
jobs:
  lint:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          command: |
              pip3 install tox
      - run:
          name: Lint
          command: |
            tox -e lint
  test_py38:
    docker:
      - image: fkrull/multi-python:latest
    steps:
      - checkout
      - run:
          name: Run tests on 3.8
          command: |
            pip3 install tox tox-pyenv
            tox -e py38
  test_py39:
    docker:
      - image: fkrull/multi-python:latest
    steps:
      - checkout
      - run:
          name: Run tests on 3.9
          command: |
            pip3 install tox tox-pyenv
            tox -e py39
  test_py310:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install tox
          command: |
            pip3 install tox
      - run:
          name: run tests
          command: |
              tox -e py310
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          command: |
            python3 -m pip install --upgrade build
            python3 -m build
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist
            - build

  pypi_publish:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout  # checkout source code to working directory
      - attach_workspace:
          at: ~/project/
      - run:
          name: verify
          command: |
            pip install -e .
            python -c 'from airflow_provider_hex import verify; verify()'
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPY_TOKEN" >> ~/.pypirc
      - run:
          command: |  # create whl, install twine and publish to PyPI
            python3 -m pip install --upgrade build twine
            python3 -m build
            pip3 install twine
            twine upload --verbose dist/*
workflows:

  build:
    jobs:
      - lint
      - build:
          filters:
            tags:
              only: /.*/
      - test_py38:
          filters:
            tags:
              only: /.*/
      - test_py39:
          filters:
            tags:
              only: /.*/
      - test_py310:
          filters:
            tags:
              only: /.*/
      - pypi_publish:
          requires:
            - build
            - test_py38
            - test_py39
            - test_py310
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9].+/
